development:
  adapter: postgresql
  database: loc8te_dev
  pool: 5
  timeout: 5000
  username: jep
  password: jepjep

test:
  adapter: postgresql
  database: loc8te_test
  pool: 5
  timeout: 5000
  username: jep
  password: jepjep

production:
  adapter: postgresql
  database: loc8te_prod
  pool: 5
  timeout: 5000